# what is it do
---
- name: docker_container
  hosts: all
  become: true
  gather_facts: true
  roles:
    - docker
  vars:
    create_containers: 1
    default_container_name: docker
    default_container_image: hello-world
    default_container_command: sleep 1d
